version: "3"
services:
  selenium:
    image: seleniarm/standalone-chromium
    ports:
      - 4444:4444
      - 7900:7900
    shm_size: "2gb"
  app:
    build: .
    volumes:
      - .:/app
    environment:
      SELENIUM_URL: http://selenium:4444/wd/hub
    env_file:
      - .env
    tty: true